allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    longhorn.io/last-applied-configmap: "kind: StorageClass\napiVersion: storage.k8s.io/v1\n\
      metadata:\n  name: longhorn\n  annotations:\n    storageclass.kubernetes.io/is-default-class:\
      \ \"true\"\nprovisioner: driver.longhorn.io\nallowVolumeExpansion: true\nreclaimPolicy:\
      \ \"Delete\"\nvolumeBindingMode: Immediate\nparameters:\n  numberOfReplicas:\
      \ \"3\"\n  staleReplicaTimeout: \"30\"\n  fromBackup: \"\"\n  fsType: \"ext4\"\
      \n  dataLocality: \"disabled\"\n  unmapMarkSnapChainRemoved: \"ignored\"\n"
    storageclass.kubernetes.io/is-default-class: 'true'
  name: longhorn
parameters:
  dataLocality: disabled
  fromBackup: ''
  fsType: ext4
  numberOfReplicas: '3'
  staleReplicaTimeout: '30'
  unmapMarkSnapChainRemoved: ignored
provisioner: driver.longhorn.io
reclaimPolicy: Delete
volumeBindingMode: Immediate
