apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: llm-gateways
  namespace: argocd
spec:
  destination:
    namespace: agentgateway-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: gateways
    repoURL: https://github.com/ProfessorSeb/k8s-rooster
    targetRevision: feature/repo-cleanup-and-config-extraction
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true