apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: model-priority-gateway
  namespace: argocd
spec:
  destination:
    namespace: agentgateway-system
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/ProfessorSeb/k8s-rooster.git
    targetRevision: main
    path: gateways/model-priority
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
