apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - gh-gateway.yaml
  #- backend/github-mcp-backend.yaml
  #- routes/github-mcp-route.yaml

commonLabels:
  app.kubernetes.io/name: github-mcp
  app.kubernetes.io/component: agentgateway-mcp

namespace: agentgateway-system
