apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backend.yaml
  - route.yaml

commonLabels:
  app.kubernetes.io/name: openai-gateway
  app.kubernetes.io/component: agentgateway

namespace: agentgateway-system
