apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - slack-mcp.yaml

commonLabels:
  app.kubernetes.io/name: kagent-slack-bot
  app.kubernetes.io/component: slack-bot

namespace: kagent
