apiVersion: v1
kind: Service
metadata:
  name: slack-mcp
  namespace: agentgateway-system
  labels:
    app: slack-mcp
spec:
  selector:
    app: slack-mcp
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    appProtocol: kgateway.dev/mcp
  type: ClusterIP
