apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - gateway.yaml
  - tracing-params.yaml
  - openai/secret.yaml
  - openai/backend.yaml
  - openai/route.yaml
  - anthropic/secret.yaml
  - anthropic/backend.yaml
  - anthropic/route.yaml
  - xai/secret.yaml
  - xai/backend.yaml
  - xai/route.yaml

commonLabels:
  app.kubernetes.io/name: llm-gateways
  app.kubernetes.io/component: agentgateway

namespace: agentgateway-system