apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - shared/
  - everything/
  - github/
  - slack/
  - excalidraw/

commonLabels:
  app.kubernetes.io/name: mcp-servers
  app.kubernetes.io/component: agentgateway-mcp

namespace: agentgateway-system
