apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - gateway.yaml
  - mcp-server-everything/deployment.yaml
  - mcp-server-everything/service.yaml
  - backend/mcp-backend.yaml
  - routes/mcp-route.yaml

commonLabels:
  app.kubernetes.io/name: mcp-servers
  app.kubernetes.io/component: agentgateway-mcp

namespace: agentgateway-system