apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - gateway.yaml
  - backend.yaml
  - route.yaml

commonLabels:
  app.kubernetes.io/name: model-priority-gateway
  app.kubernetes.io/component: agentgateway

namespace: agentgateway-system
