apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - slackbot-k8s-agent.yaml
  - github-issues-agent.yaml
  - github-pr-agent.yaml
  - team-lead-agent.yaml

commonLabels:
  app.kubernetes.io/name: kagent-agents
  app.kubernetes.io/component: agents

namespace: kagent
