apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - kagent-slack-bot-deployment.yaml
  #- slack-mcp.yaml
  - slackbot-k8s-agent.yaml
  - github-mcp-remote.yaml
  - github-issues-agent.yaml
  - github-pr-agent.yaml

commonLabels:
  app.kubernetes.io/name: kagent-agents
  app.kubernetes.io/component: agents

namespace: kagent
