apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - xai-grok-config.yaml
  - claude-model-config.yaml
  - llm-agentgateway.yaml
  - gemini-model-config.yaml

commonLabels:
  app.kubernetes.io/name: kagent-models
  app.kubernetes.io/component: model-configs

namespace: kagent
